import { readFileSync, writeFileSync, existsSync, mkdirSync, chmodSync } from "fs";
import { resolve } from "path";
import { homedir } from "os";
import { execSync } from "child_process";

export const APP_DIR = resolve(homedir(), ".deepseek-lane");
export const CONFIG_PATH = resolve(APP_DIR, "config.yaml");
export const PID_PATH = resolve(APP_DIR, "pid");
export const LOG_PATH = resolve(APP_DIR, "log");

export function ensureDir(): void {
  if (!existsSync(APP_DIR)) {
    mkdirSync(APP_DIR, { recursive: true, mode: 0o700 });
  }
}

export function readPid(): number | null {
  try {
    if (existsSync(PID_PATH)) {
      const content = readFileSync(PID_PATH, "utf-8").trim();
      if (content) {
        const pid = parseInt(content, 10);
        if (!isNaN(pid)) return pid;
      }
    }
  } catch {}
  try {
    const stdout = execSync('pgrep -f "^node.*deepseek-lane.*start"', { encoding: "utf-8" });
    const lines = stdout.trim().split("\n").filter(Boolean).map(Number);
    if (lines.length > 0) return lines[lines.length - 1];
  } catch {}
  return null;
}

export function isRunning(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

export function isServerRunning(): boolean {
  const pid = readPid();
  return pid !== null && isRunning(pid);
}

export function detectNgrokUrl(): string | null {
  try {
    if (existsSync(LOG_PATH)) {
      const log = readFileSync(LOG_PATH, "utf-8");
      const m = log.match(/https:\/\/[a-z0-9-]+\.ngrok-free\.dev\/v1/i);
      if (m) return m[0];
    }
  } catch {}
  return null;
}

export function writeConfig(config: Record<string, unknown>): void {
  ensureDir();
  const yaml = Object.entries(config).map(([k, v]) => `${k}: ${String(v)}`);
  yaml.unshift("# deepseek-lane config");
  yaml.unshift("# Generated by: dsl start");
  writeFileSync(CONFIG_PATH, yaml.join("\n") + "\n", "utf-8");
  chmodSync(CONFIG_PATH, 0o600);
}

export function writePidFile(pid?: number): void {
  ensureDir();
  writeFileSync(PID_PATH, String(pid ?? process.pid), "utf-8");
}

export function removePidFile(): void {
  try {
    if (existsSync(PID_PATH)) {
      writeFileSync(PID_PATH, "", "utf-8");
    }
  } catch {}
}

export function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}
